
jobs:
- job: sitl
  displayName: 'Windows Cygwin SITL build'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: choco install cygwin --params "/InstallDir:C\Cygwin /NoStartMenu /NoAdmin"
    displayName: 'Install Cygwin'
  - script: choco install gcc-g++ libxml2-devel libxslt-devel python2-devel python2-future python2-libxml2 python2-pip --source cygwin
    displayName: 'Install Cygwin packages'
  - script: C:\Cygwin\bin\bash --login './waf all'
    displayName: 'Build SITL'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'Build artifacts'
      targetPath: 'build/sitl/bin'
